on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: '14.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up a jupyter notebook in background
        run: |
          docker build -f docker/Dockerfile -t forax/amber-record .
          docker run -d -p 8888:8888 forax/amber-record bash travis/script.sh
      - name: Install
        run: |
          npm install decktape
          java pro_wrapper.java version
      - name: Run build
        run: |
          ./pro/bin/pro
          npm bin
          java publish/print_slideshow.java
      - name: Upload slide
        uses: actions/upload-artifact@v2
        with:
          name: Slide
          path: pdf
