name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install and build
      run: |
        java pro_wrapper.java version
        ./pro/bin/pro
